name: Build Astro following official Github Actions beta

on:
  # Runs on pushes targeting the default branch
  push:
    branches: [ main ] # publish from main branch since we have dev repo
    tags: [ gh-publish ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true
  
jobs:
  build:    
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        
      - name: Build site 🔧 
        run: |
          npm i 
          npm run build 
          # removed for domain tapggc.org: -- --base /tap-ws1-astro-agnosticui

      - name: Upload site ↗️
        uses: actions/upload-pages-artifact@v3
        with: 
          path: dist/
  
  deploy:      
    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }} 
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages 🚀
        id: deployment
        uses: actions/deploy-pages@v4
